const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='lineupMaker.pwa.v1';
const POS=['투수','포수','1루수','2루수','3루수','유격수','좌익수','중견수','우익수','지명타자','없음'];
const FIELD_POS=POS.slice(0,9);
const coords={투수:[.50,.56],포수:[.50,.84],'1루수':[.71,.59],'2루수':[.62,.43],'3루수':[.29,.59],유격수:[.41,.43],좌익수:[.26,.26],중견수:[.50,.18],우익수:[.74,.26],지명타자:[.30,.78]};
const offsets={투수:[0,-20],포수:[-5,-20],'1루수':[0,-30],'3루수':[0,-30],유격수:[-35,0],지명타자:[0,-30]};
const dict={ko:{position:'포지션',lineup:'라인업',settings:'설정',starters:'선발',bench:'벤치',teamSettings:'팀 설정',teamName:'팀명',defaultPlayers:'기본 출전 선수',dh:'지명타자',use:'사용',notUse:'미사용',benchPosition:'포지션 탭 벤치멤버',show:'보이기',hide:'숨기기',language:'언어',playerManagement:'선수 관리',number:'등번호',name:'이름'},en:{position:'Positions',lineup:'Lineup',settings:'Settings',starters:'Starters',bench:'Bench',teamSettings:'Team Settings',teamName:'Team Name',defaultPlayers:'Default Players',dh:'Designated Hitter',use:'Use',notUse:'Off',benchPosition:'Bench on Field',show:'Show',hide:'Hide',language:'Language',playerManagement:'Players',number:'No.',name:'Name'},ja:{position:'守備位置',lineup:'ラインナップ',settings:'設定',starters:'スタメン',bench:'ベンチ',teamSettings:'チーム設定',teamName:'チーム名',defaultPlayers:'基本出場人数',dh:'指名打者',use:'使用',notUse:'未使用',benchPosition:'守備画面ベンチ',show:'表示',hide:'非表示',language:'言語',playerManagement:'選手管理',number:'背番号',name:'名前'}};
const posLabel=(p,l)=>({en:{투수:'Pitcher',포수:'Catcher','1루수':'1B','2루수':'2B','3루수':'3B',유격수:'SS',좌익수:'LF',중견수:'CF',우익수:'RF',지명타자:'DH',없음:'None'},ja:{투수:'投手',포수:'捕手','1루수':'一塁手','2루수':'二塁手','3루수':'三塁手',유격수:'遊撃手',좌익수:'左翼手',중견수:'中堅手',우익수:'右翼手',지명타자:'指名打者',없음:'なし'}}[l]?.[p]||p);
const demoPlayers=[['1','김도윤','투수'],['2','박준혁','포수'],['3','이민호','1루수'],['4','최성훈','2루수'],['5','정상훈','3루수'],['6','한지우','유격수'],['7','오태양','좌익수'],['8','윤재민','중견수'],['9','서현우','우익수'],['10','강민석','지명타자'],['11','문재훈','3루수'],['17','임성준','외야'],['23','배진수','포수']].map((x,i)=>({id:'p'+i,num:x[0],name:x[1],primary:POS.includes(x[2])?x[2]:'없음'}));
const fresh=()=>({lang:null,gameTitle:'7월 31일 vs 블루삭스',teamName:'블루삭스',defaultCount:9,usesDH:true,showBench:true,players:demoPlayers,starters:demoPlayers.slice(0,10).map((p,i)=>({id:'s'+i,playerId:p.id,position:i<10?p.primary:'없음'})),bench:demoPlayers.slice(10).map((p,i)=>({id:'b'+i,playerId:p.id,position:'없음'})),saved:[]});
let state; try{state=JSON.parse(localStorage.getItem(KEY))||fresh()}catch{state=fresh()}
let undo=[],redo=[];
function snapshot(){undo.push(JSON.stringify(state));if(undo.length>50)undo.shift();redo=[]}
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function commit(){persist();renderAll()}
function player(id){return state.players.find(p=>p.id===id)}
function t(k){return dict[state.lang||'ko'][k]||dict.ko[k]||k}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function optionsPlayers(selected){return `<option value="">—</option>`+state.players.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>#${p.num} ${esc(p.name)}</option>`).join('')}
function optionsPos(selected){return POS.filter(p=>state.usesDH||p!=='지명타자').map(p=>`<option value="${p}" ${p===selected?'selected':''}>${posLabel(p,state.lang)}</option>`).join('')}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderAll(){applyI18n();$('#gameTitle').value=state.gameTitle;renderField();renderPortrait();renderEditors();renderSettings();renderWarnings();$('#undoBtn').disabled=!undo.length;$('#redoBtn').disabled=!redo.length}
function applyI18n(){$$('[data-i]').forEach(e=>e.textContent=t(e.dataset.i));$('#languageSelect').value=state.lang||'ko';document.documentElement.lang=state.lang||'ko'}
function renderField(){const markers=$('#markers');markers.innerHTML='';const field=$('#field');const offsetScale=Math.min(1,Math.max(.34,field.clientWidth/900));const positions=[...FIELD_POS,...(state.usesDH?['지명타자']:[])];positions.forEach(pos=>{const entry=state.starters.find(x=>x.position===pos),p=entry&&player(entry.playerId);const [x,y]=coords[pos], [ox,oy]=offsets[pos]||[0,0];const m=document.createElement('div');m.className='marker '+(!p?'empty':'');m.dataset.dropPosition=pos;m.style.left=`calc(${x*100}% + ${Math.round(ox*offsetScale)}px)`;m.style.top=`calc(${y*100}% + ${Math.round(oy*offsetScale)}px)`;m.innerHTML=`<strong>${p?`#${esc(p.num)} ${esc(p.name)}`:posLabel(pos,state.lang)}</strong><small>${posLabel(pos,state.lang)}</small>`;if(entry){setupDrag(m,{type:'entry',id:entry.id,source:'starter'})}markers.appendChild(m)});const bp=$('#benchPanel');bp.style.display=state.showBench?'block':'none';bp.innerHTML=`<h3>${t('bench')}</h3>`+state.bench.slice(0,8).map(e=>{const p=player(e.playerId);return `<div class="bench-mini" data-bench-id="${e.id}"><span>${p?.num||'-'}</span><span>${esc(p?.name||'—')}</span></div>`}).join('');$$('[data-bench-id]').forEach(el=>setupDrag(el,{type:'entry',id:el.dataset.benchId,source:'bench'}));bp.dataset.dropBench='1'}
function renderPortrait(){const host=$('#portraitTable');host.innerHTML=`<div class="portrait-lineup"><h3>${t('starters')}</h3><div class="portrait-head"><span>#</span><span>${t('number')}</span><span>${t('name')}</span><span>${t('position')}</span></div><div id="pStart"></div><div class="bench-divider"></div><h3>${t('bench')}</h3><div class="portrait-head"><span></span><span>${t('number')}</span><span>${t('name')}</span><span>${t('position')}</span></div><div id="pBench"></div></div>`;state.starters.forEach((e,i)=>{$('#pStart').insertAdjacentHTML('beforeend',portraitRow(e,i,'starter'))});state.bench.forEach((e,i)=>{$('#pBench').insertAdjacentHTML('beforeend',portraitRow(e,i,'bench'))});$$('.name-drag').forEach(el=>setupDrag(el,{type:'order',id:el.dataset.id,source:el.dataset.source}));$$('.pos-drag').forEach(el=>setupDrag(el,{type:'positionCell',id:el.dataset.id,source:el.dataset.source}));$$('[data-drop-row]').forEach(el=>el.dataset.dropRow=el.dataset.dropRow)}
function portraitRow(e,i,source){const p=player(e.playerId);return `<div class="portrait-row" data-drop-row="${e.id}" data-source="${source}"><span>${source==='starter'?i+1:''}</span><span>${p?.num||'-'}</span><span class="drag-cell name-drag" data-id="${e.id}" data-source="${source}">${esc(p?.name||'—')}</span><span class="drag-cell pos-drag" data-id="${e.id}" data-source="${source}">${posLabel(source==='bench'?p?.primary||'없음':e.position,state.lang)}</span></div>`}
function renderEditors(){const s=$('#starterEditor');s.innerHTML=`<div class="table-head"><span>타순</span><span>${t('number')}</span><span>${t('name')}</span><span>${t('position')}</span><span></span></div>`;state.starters.forEach((e,i)=>{const p=player(e.playerId);s.insertAdjacentHTML('beforeend',`<div class="starter-row" data-sid="${e.id}"><div class="order">${i+1}</div><div class="number">${p?.num||'—'}</div><select class="playerSelect">${optionsPlayers(e.playerId)}</select><select class="posSelect">${optionsPos(e.position)}</select><button class="remove">×</button></div>`)});const b=$('#benchEditor');b.innerHTML=`<div class="bench-head"><span>${t('number')}</span><span>${t('name')}</span><span></span></div>`;state.bench.forEach(e=>{const p=player(e.playerId);b.insertAdjacentHTML('beforeend',`<div class="bench-row" data-bid="${e.id}"><div class="number">${p?.num||'—'}</div><select>${optionsPlayers(e.playerId)}</select><button class="remove">×</button></div>`)});$$('[data-sid]').forEach(row=>{const e=state.starters.find(x=>x.id===row.dataset.sid);row.querySelector('.playerSelect').onchange=ev=>{snapshot();e.playerId=ev.target.value;commit()};row.querySelector('.posSelect').onchange=ev=>{snapshot();e.position=ev.target.value;commit()};row.querySelector('.remove').onclick=()=>{snapshot();state.starters=state.starters.filter(x=>x.id!==e.id);commit()}});$$('[data-bid]').forEach(row=>{const e=state.bench.find(x=>x.id===row.dataset.bid);row.querySelector('select').onchange=ev=>{snapshot();e.playerId=ev.target.value;commit()};row.querySelector('.remove').onclick=()=>{snapshot();state.bench=state.bench.filter(x=>x.id!==e.id);commit()}})}
function renderSettings(){for(let i=9;i<=30;i++)if(![...$('#defaultCount').options].some(o=>+o.value===i))$('#defaultCount').add(new Option(i,i));$('#teamName').value=state.teamName;$('#defaultCount').value=state.defaultCount;$$('input[name=dh]').forEach(r=>r.checked=(r.value==='on')===state.usesDH);$$('input[name=showBench]').forEach(r=>r.checked=(r.value==='on')===state.showBench);const pm=$('#playerManager');pm.innerHTML='';state.players.forEach(p=>pm.insertAdjacentHTML('beforeend',`<div class="player-row" data-pid="${p.id}"><input class="pnum" value="${esc(p.num)}"><input class="pname" value="${esc(p.name)}"><select class="ppos">${optionsPos(p.primary)}</select><button class="remove">×</button></div>`));$$('[data-pid]').forEach(row=>{const p=player(row.dataset.pid);row.querySelector('.pnum').onchange=e=>{snapshot();p.num=e.target.value;commit()};row.querySelector('.pname').onchange=e=>{snapshot();p.name=e.target.value;commit()};row.querySelector('.ppos').onchange=e=>{snapshot();p.primary=e.target.value;commit()};row.querySelector('.remove').onclick=()=>{snapshot();state.players=state.players.filter(x=>x.id!==p.id);state.starters.forEach(x=>{if(x.playerId===p.id)x.playerId=''});state.bench.forEach(x=>{if(x.playerId===p.id)x.playerId=''});commit()}});const sg=$('#savedGames');sg.innerHTML='<h3>저장된 경기</h3>'+state.saved.map((g,i)=>`<div class="saved-game"><span>${esc(g.gameTitle)}</span><button data-load="${i}">불러오기</button><button data-copy="${i}">복사</button><button data-del="${i}">삭제</button></div>`).join('');$$('[data-load]').forEach(b=>b.onclick=()=>{snapshot();Object.assign(state,JSON.parse(JSON.stringify(state.saved[+b.dataset.load])));state.saved=JSON.parse(localStorage.getItem(KEY)).saved||state.saved;commit()});$$('[data-copy]').forEach(b=>{b.onclick=()=>{const g=JSON.parse(JSON.stringify(state.saved[+b.dataset.copy]));g.gameTitle+=' 복사본';g.starters.forEach(x=>x.id=crypto.randomUUID());g.bench.forEach(x=>x.id=crypto.randomUUID());snapshot();Object.assign(state,g);commit()}});$$('[data-del]').forEach(b=>b.onclick=()=>{snapshot();state.saved.splice(+b.dataset.del,1);commit()})}
function renderWarnings(){const dupPos=state.starters.map(e=>e.position).filter(p=>p!=='없음'&&p!=='지명타자').filter((p,i,a)=>a.indexOf(p)!==i);const used=state.starters.map(e=>e.position);const miss=FIELD_POS.filter(p=>!used.includes(p));const ids=state.starters.concat(state.bench).map(e=>e.playerId).filter(Boolean),dupPlayers=ids.filter((x,i,a)=>a.indexOf(x)!==i);const msgs=[];if(dupPos.length)msgs.push('중복 포지션: '+[...new Set(dupPos)].join(', '));if(miss.length)msgs.push('빠진 포지션: '+miss.join(', '));if(dupPlayers.length)msgs.push('중복 선수 배치');$('#warnings').textContent=msgs.join(' · ')}
function handleDrop(payload,target){snapshot();const sourceArr=payload.source==='bench'?state.bench:state.starters;const src=sourceArr.find(x=>x.id===payload.id);if(!src)return; if(target.kind==='position'){const dst=state.starters.find(x=>x.position===target.position);if(payload.source==='bench'){state.bench=state.bench.filter(x=>x.id!==src.id);if(dst){state.starters=state.starters.filter(x=>x.id!==dst.id);state.bench.push({...dst,position:'없음'})}state.starters.push({...src,position:target.position})}else{if(dst&&dst.id!==src.id){const temp=src.position;src.position=dst.position;dst.position=temp}else src.position=target.position}}else if(target.kind==='bench'){if(payload.source==='starter'){state.starters=state.starters.filter(x=>x.id!==src.id);state.bench.push({...src,position:'없음'})}}else if(target.kind==='row'){const targetArr=target.source==='bench'?state.bench:state.starters;const dst=targetArr.find(x=>x.id===target.id);if(!dst)return;if(payload.type==='order'&&payload.source==='starter'&&target.source==='starter'){const a=state.starters.findIndex(x=>x.id===src.id),b=state.starters.findIndex(x=>x.id===dst.id);state.starters.splice(b,0,state.starters.splice(a,1)[0])}else if(payload.type==='positionCell'&&payload.source==='starter'&&target.source==='starter'){[src.position,dst.position]=[dst.position,src.position]}else if(payload.source!==target.source){if(payload.source==='bench'){state.bench=state.bench.filter(x=>x.id!==src.id);state.starters=state.starters.filter(x=>x.id!==dst.id);state.starters.push({...src,position:dst.position});state.bench.push({...dst,position:'없음'})}else{state.starters=state.starters.filter(x=>x.id!==src.id);state.bench=state.bench.filter(x=>x.id!==dst.id);state.bench.push({...src,position:'없음'});state.starters.push({...dst,position:src.position})}}}commit()}
let drag=null;
function setupDrag(el,payload){el.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0)return;drag={payload,startX:e.clientX,startY:e.clientY,el};el.setPointerCapture?.(e.pointerId);const g=$('#dragGhost');g.textContent=el.textContent.trim();g.classList.remove('hidden');moveGhost(e);e.preventDefault()};el.onpointermove=e=>{if(!drag||drag.el!==el)return;moveGhost(e);highlightTarget(e.clientX,e.clientY)};el.onpointerup=e=>{if(!drag||drag.el!==el)return;const target=findTarget(e.clientX,e.clientY);clearDrag();if(target)handleDrop(payload,target)};el.onpointercancel=clearDrag}
function moveGhost(e){const g=$('#dragGhost');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}
function findTarget(x,y){const elems=document.elementsFromPoint(x,y);const pos=elems.find(e=>e.dataset?.dropPosition);if(pos)return{kind:'position',position:pos.dataset.dropPosition};if(elems.find(e=>e.dataset?.dropBench))return{kind:'bench'};const row=elems.find(e=>e.dataset?.dropRow);if(row)return{kind:'row',id:row.dataset.dropRow,source:row.dataset.source};return null}
function highlightTarget(x,y){$$('.drop-hover').forEach(e=>e.classList.remove('drop-hover'));const elems=document.elementsFromPoint(x,y);const e=elems.find(e=>e.dataset?.dropPosition||e.dataset?.dropBench||e.dataset?.dropRow);e?.classList.add('drop-hover')}
function clearDrag(){$('#dragGhost').classList.add('hidden');$$('.drop-hover').forEach(e=>e.classList.remove('drop-hover'));drag=null}
function generateImage(){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1200;c.height=800;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,1200,800);ctx.font='bold 23px -apple-system';ctx.textAlign='center';state.starters.forEach(e=>{if(!coords[e.position])return;const p=player(e.playerId);if(!p)return;const [x,y]=coords[e.position],[ox,oy]=offsets[e.position]||[0,0];const px=x*1200+ox*1.6,py=y*800+oy*1.6;ctx.fillStyle='rgba(15,25,38,.92)';roundRect(ctx,px-72,py-29,144,58,14);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.fillText(`#${p.num} ${p.name}`,px,py-2);ctx.font='18px -apple-system';ctx.fillText(posLabel(e.position,state.lang),px,py+20);ctx.font='bold 23px -apple-system'});c.toBlob(resolve,'image/png')};img.onerror=reject;img.src='baseball-field.png'})}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h))}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(t=>t.classList.toggle('active',t.id===b.dataset.tab))});
$('#gameTitle').onchange=e=>{snapshot();state.gameTitle=e.target.value;commit()};$('#saveGameBtn').onclick=()=>{state.saved.push(JSON.parse(JSON.stringify({...state,saved:undefined})));persist();renderSettings();toast('저장했어요')};$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(JSON.stringify(state));state=JSON.parse(undo.pop());commit()};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(JSON.stringify(state));state=JSON.parse(redo.pop());commit()};$('#addStarter').onclick=()=>{if(state.starters.length>=30)return toast('더 이상 추가할 수 없어요');snapshot();state.starters.push({id:crypto.randomUUID(),playerId:'',position:'없음'});commit()};$('#addBench').onclick=()=>{snapshot();state.bench.push({id:crypto.randomUUID(),playerId:'',position:'없음'});commit()};$('#addPlayer').onclick=()=>{snapshot();state.players.push({id:crypto.randomUUID(),num:'',name:'새 선수',primary:'없음'});commit()};$('#teamName').onchange=e=>{snapshot();state.teamName=e.target.value;commit()};$('#defaultCount').onchange=e=>{snapshot();state.defaultCount=+e.target.value;commit()};$$('input[name=dh]').forEach(r=>r.onchange=e=>{snapshot();state.usesDH=e.target.value==='on';if(!state.usesDH)state.starters.forEach(x=>{if(x.position==='지명타자')x.position='없음'});commit()});$$('input[name=showBench]').forEach(r=>r.onchange=e=>{snapshot();state.showBench=e.target.value==='on';commit()});$('#languageSelect').onchange=e=>{state.lang=e.target.value;commit()};$('#exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='lineup-maker-backup.json';a.click()};$('#importJson').onchange=async e=>{try{snapshot();state=JSON.parse(await e.target.files[0].text());commit();toast('복원했어요')}catch{toast('복원 실패')}};$('#resetData').onclick=()=>{if(confirm('전체 데이터를 초기화할까요?')){state=fresh();commit()}};$('#shareBtn').onclick=async()=>{const blob=await generateImage();const file=new File([blob],'lineup.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:state.gameTitle,files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lineup.png';a.click()}};
$$('#languageGate button').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;$('#languageGate').classList.add('hidden');commit()});if(!state.lang)$('#languageGate').classList.remove('hidden');if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));renderAll();

let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if($('#positionTab').classList.contains('active')){renderField();}},120)});
